### ISSUE TITLE
Error in RedsysController.php

### ISSUE THREAD

**Issue by SHI1989** [macklus/yii2-payments#6]
I found this error when access to response data for writting redsys.log

yii\base\ErrorException: Illegal string offset 'Ds_Response' in /var/www/vhosts/ruedascustom.com/httpdocs/vendor/macklus/yii2-payments/controllers/RedsysController.php:97

**Comment by macklus** [comment]
Ds_Response variable should be send by RedSys to us, with the corresponding data.

when this error appears, wich type of transaction did you run ? 

- Full and correct payment
- Cancelled payment
- Wrong / interrupted payment
- other

i suppose that problem here is that type of transaction is not well tested

**Comment by SHI1989** [comment]
I was doing a payment with error test card that redsys give us for api
testing.

Card number:  1111111111111117

Expired:    12/20


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-16 8:21 GMT+01:00 José Pedro Andrés <notifications@github.com>:

**Comment by macklus** [comment]
Im pretty sure problem is resolv by now, after some changes... but i cant test if because test environment on redsys.es is not function well.

I update code soon, sorry about the delay
